AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Gateway function to score the ML model.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: gateway.lambda_handler
      Runtime: python3.8
      CodeUri: ../src/.
      Description: Call the AWS Lambda API
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
#        - AWSLambda_AllowTargetScorerRole
#        - arn:aws:iam::819883234898:role/AllowTargetScorerRole
      Tracing: Active
      Layers:
        - !Ref libs
      Environment:
        Variables:
          SCORING_LAMBDA: !Ref ScoringLambdaARN
          PHASE: !Ref Phase
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: gateway-deps
      Description: Dependencies for the sample app.
      ContentUri: ../package/.
      CompatibleRuntimes:
        - python3.8
Parameters:
  ScoringLambdaARN:
    Type: String
  Phase:
    Type: String