AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Gateway function to score the ML model.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: scorer.lambda_handler
      Runtime: python3.8
      CodeUri: ../src/.
      Description: Call the AWS Lambda API
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: scorer-deps
      Description: Dependencies for the sample app.
      ContentUri: ../package/.
      CompatibleRuntimes:
        - python3.8