name: Deploy Gateway Function to AWS
on:
  push:
    branches:
      - main
jobs:
  tests:
    uses: ./.github/workflows/build-gateway.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: bash function-gateway/scripts/build-layer.sh # build dependencies
      - run: bash function-gateway/scripts/deploy.sh
